-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQraZud0soYL82CU0
PcUBMCXqvyrq8nIZs5BJoe0OnE2gCgYIKoZIzj0DAQehRANCAAQ6jIt5tZXiVmiG
dsrL5CKkCCnfy4F6J+YdoEPAVegu/Xar1Hd09iLTVctn+EhH8+1SSqIktgqtDMp7
lQzZXqTe
-----END PRIVATE KEY-----